service: serverless-code-test

frameworkVersion: "^3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  timeout: 60
  stage: dev
  versionFunctions: false

functions:

plugins:
  - serverless-mocha-plugin
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    httpPort: 3001
  webpackIncludeModules:
    packagePath: './package.json'
